### ISSUE TITLE
Like your idea, but ...

### ISSUE THREAD

**Issue by wimmelstein** [Zarmina/JavaFundamentals#1]
Nowhere do I ask you to implement code for the login button, let alone create a model, a database and a service. Overdoing it may sound nice, but in the real world it is taking up a lot of time, and raises the bar for any stakeholders of the application.

Also... please don't put so many empty lines in your code. It makes me scroll a lot more, and I lose overview. In Java the opening braces of classes, methods and if statements come at the end of the line, not on the next...

Kind regards,
Wim Wiltenburg

**Comment by Zarmina** [comment]
Dear Wim @wimmelstein ,
thank you very much for your input, I completely understand your point about overdoing things but since I wasnt in classes (due to year 4 projects and classes) I thought it might be necessary so I preferred to be safe than sorry.
sorry about the empty lines, I can understand it can be annoying.
and about the bracing style I think we can blame Gerwin van Dijken for teaching me C# before Java :D .

**Comment by wimmelstein** [comment]
No, C# has the braces on the new line. Java doesn't.
